
package:
  name: Maldact
  version: "0.1.0"

source:
  path: ..

build:
  script: "{{ PYTHON }} -m pip install . --no-deps"
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - asttokens=2.4.1
    - attrs=23.2.0
    - backcall=0.2.0
    - beautifulsoup4=4.12.3
    - blas=1.0
    - bleach=6.1.0
    - brotli=1.0.9
    - brotli-bin=1.0.9
    - bzip2=1.0.8
    - ca-certificates=2024.3.11
    - certifi=2024.7.4
    - charset-normalizer=3.3.2
    - colorama=0.4.6
    - contourpy=1.2.0
    - cuda-cudart=12.0.107
    - cuda-cudart_win-64=12.0.107
    - cuda-nvrtc=12.0.76
    - cuda-version=12.0
    - cupy=12.2.0
    - cycler=0.11.0
    - decorator=5.1.1
    - defusedxml=0.7.1
    - docopt=0.6.2
    - executing=2.0.1
    - fastjsonschema=2.20.0
    - fastrlock=0.8.2
    - fonttools=4.25.0
    - freetype=2.12.1
    - giflib=5.2.1
    - icc_rt=2022.1.0
    - icu=73.1
    - idna=3.7
    - iniconfig=1.1.1
    - intel-openmp=2023.1.0
    - ipython=8.12.3
    - jedi=0.19.1
    - jinja2=3.1.4
    - jpeg=9e
    - jsonschema=4.23.0
    - jsonschema-specifications=2023.12.1
    - jupyter-client=8.6.2
    - jupyter-core=5.7.2
    - jupyterlab-pygments=0.3.0
    - kiwisolver=1.4.4
    - krb5=1.20.1
    - lerc=3.0
    - libbrotlicommon=1.0.9
    - libbrotlidec=1.0.9
    - libbrotlienc=1.0.9
    - libclang=14.0.6
    - libclang13=14.0.6
    - libcublas=12.0.1.189
    - libcufft=11.0.0.21
    - libcurand=10.3.1.50
    - libcusolver=11.4.2.57
    - libcusparse=12.0.0.76
    - libdeflate=1.17
    - libffi=3.4.4
    - libnvjitlink=12.0.76
    - libpng=1.6.39
    - libpq=12.15
    - libtiff=4.5.1
    - libwebp=1.3.2
    - libwebp-base=1.3.2
    - lz4-c=1.9.4
    - markupsafe=2.1.5
    - matplotlib=3.8.0
    - matplotlib-base=3.8.0
    - matplotlib-inline=0.1.7
    - mistune=3.0.2
    - mkl=2023.1.0
    - mkl-service=2.4.0
    - mkl_fft=1.3.8
    - mkl_random=1.2.4
    - munkres=1.1.4
    - nbclient=0.10.0
    - nbconvert=7.16.4
    - nbformat=5.10.4
    - numpy=1.26.0
    - numpy-base=1.26.0
    - openjpeg=2.4.0
    - openssl=3.1.4
    - packaging=23.1
    - pandocfilters=1.5.1
    - parso=0.8.4
    - pickleshare=0.7.5
    - pillow=10.0.1
    - pip=23.3
    - pipreqs=0.5.0
    - platformdirs=4.2.2
    - pluggy=1.0.0
    - ply=3.11
    - prompt-toolkit=3.0.47
    - pure-eval=0.2.2
    - pybind11-abi=5
    - pygments=2.18.0
    - pyparsing=3.0.9
    - pyqt=5.15.10
    - pyqt5-sip=12.13.0
    - pytest=7.4.0
    - python=3.11.5
    - python-dateutil=2.8.2
    - python_abi=3.11
    - pywin32=306
    - pyzmq=26.0.3
    - qt-main=5.15.2
    - referencing=0.35.1
    - requests=2.32.3
    - rpds-py=0.19.0
    - scipy=1.13.0
    - setuptools=68.0.0
    - sip=6.7.12
    - six=1.16.0
    - soupsieve=2.5
    - sqlite=3.41.2
    - stack-data=0.6.3
    - tbb=2021.8.0
    - tinycss2=1.3.0
    - tk=8.6.12
    - tornado=6.3.3
    - traitlets=5.14.3
    - tzdata=2023c
    - ucrt=10.0.22621.0
    - urllib3=2.2.2
    - vc=14.2
    - vc14_runtime=14.36.32532
    - vs2015_runtime=14.36.32532
    - wcwidth=0.2.13
    - webencodings=0.5.1
    - wheel=0.41.2
    - xz=5.4.2
    - yarg=0.1.9
    - zlib=1.2.13
    - zstd=1.5.5

test:
  imports:
    - pytest

about:
  home: https://github.com/wision-ware/Maldact
  license: MIT
  license_file: LICENSE
  summary: "Machine learning data classification tool"
  description: |
    A GUI and CLI tool used to train and use simple ANN models for classifying discrete and timeseries data.
  doc_url: https://github.com/wision-ware/Maldact
  dev_url: https://github.com/wision-ware/Maldact

extra:
  recipe-maintainers:
    - Vavrinec Kavan
