
package:
  name: maldact
  version: "0.1.0"

source:
  path: ..

build:
  entry_points:
    - maldact = main:main
    
  channels:
    - conda-forge

  number: 0

requirements:
  build:
    - python
    - pip
  run:
    # vanilla conda
    - python
    - numpy
    - matplotlib
    - pyqt
    - pytest
    # conda forge
    - cupy

test:
  imports:
    - pytest

about:
  home: https://github.com/wision-ware/Maldact
  license: MIT
  license_file: LICENSE
  summary: "Machine learning data classification tool"
  description: |
    A GUI and CLI tool used to train and use simple ANN models for classifying discrete and timeseries datasets.
  doc_url: https://github.com/wision-ware/Maldact
  dev_url: https://github.com/wision-ware/Maldact

extra:
  recipe-maintainers:
    - Vavrinec Kavan
  conda_build_config_files:
    - conda_build_config.yaml
