
package:
  name: maldact
  version: "0.1.0"

source:
  path: .

build:
  channels:
    - conda-forge

  number: 0

  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

  entry_points:
    - maldact = maldact.main:main

requirements:
  build:
    - python
    - pip
  run:
    # vanilla conda
    - python
    - numpy
    - matplotlib
    - pyqt
    - pytest
    # conda forge
    - cupy

test:
  imports:
    - maldact

about:
  home: https://github.com/wision-ware/Maldact
  license: MIT
  license_file: LICENSE
  summary: "Machine learning data classification tool"
  description: |
    A GUI and CLI tool used to train and use simple ANN models for classifying discrete and timeseries datasets.
    Specifically developed for the Department Of Space Physics ÚFA CAS.
  doc_url: https://github.com/wision-ware/Maldact
  dev_url: https://github.com/wision-ware/Maldact
  maintainers:
    - wision-ware
  authors:
    - name: Vavrinec Kavan
      email: kavan.vavrinec@gmail.com

extra:
  recipe-maintainers:
    - wision-ware
  conda_build_config_files:
    - conda_build_config.yaml
