using Microsoft.ML.Data;

namespace Maldact.Backend.ML.Modules;

/// <summary>
/// Holds the raw probability outputs generated by the ML.NET classification engine.
/// </summary>
public class TreePrediction
{
    /// <summary>
    /// The array of predicted probabilities mapped sequentially to each distinct class.
    /// </summary>
    [VectorType] 
    [ColumnName("Score")]
    public float[] Probabilities { get; set; } = [];
}