using System.Text;
using Maldact.Backend.Server.ControlProtocol.Responses;

namespace Maldact.Backend.Server.ControlProtocol.Utils;

/// <summary>
/// Highly optimized interceptor that captures standard text stream output generated by command line parsers.
/// </summary>
public sealed class CommandResultCapture : TextWriter
{
    /// <summary>
    /// Gets or sets the expected resolution state of the captured command.
    /// </summary>
    public CommandResponse.Type ResultType { get; set; } = CommandResponse.Type.Ok;

    private readonly StringBuilder _sb = new();
    
    /// <inheritdoc />
    public override void Write(char value) => _sb.Append(value);

    /// <inheritdoc />
    public override void Write(string? value) => _sb.Append(value);

    /// <summary>
    /// Parses the captured text stream into a structured command response without allocating large intermediate arrays.
    /// </summary>
    /// <returns>A strongly typed response representing the command execution.</returns>
    /// <exception cref="InvalidOperationException">Thrown if the captured output buffer is entirely empty.</exception>
    public CommandResponse GetCommandResponse()
    {
        if (_sb.Length == 0)
        {
            throw new InvalidOperationException("No output to parse from the command execution buffer.");
        }

        using var reader = new StringReader(_sb.ToString());
        
        // first line is always treated as the primary message summary
        var message = reader.ReadLine() ?? string.Empty;
        
        // the remainder is treated as the multiline payload
        var payload = reader.ReadToEnd();
        
        return new CommandResponse(
            ResultType, 
            message, 
            string.IsNullOrWhiteSpace(payload) ? null : payload.TrimEnd());
    }

    /// <summary>
    /// Purges the internal buffer, resetting it for the next capture sequence.
    /// </summary>
    public void Clear() => _sb.Clear();

    /// <inheritdoc />
    public override Encoding Encoding => Encoding.UTF8;
}