using Maldact.Core.ML;
using Maldact.Core.ML.Consolidation.Tuning;

namespace Maldact.Backend.ML.Consolidation.Tuning.Optimizers.BruteForce;

/// <summary>
/// Provides a base implementation for an exhaustive grid search optimization strategy.
/// Safely disposes iterator state machines to prevent resource leaks during large tuning sweeps.
/// </summary>
public abstract class BruteForceGridOptimizer : IConsolidatorOptimizer, IDisposable
{
    /// <summary>
    /// The standard, static permutation array of physical frame window sizes to evaluate.
    /// </summary>
    protected static readonly int[] FrameWindows = [2, 4, 8, 16, 32];
    
    /// <summary>
    /// The sampling frequency of the underlying inference data.
    /// </summary>
    protected readonly double FrameRateHz;
    
    /// <summary>
    /// The target classes mapped to the inference arrays.
    /// </summary>
    protected readonly ClassificationClass[] Classes;
    
    // private encapsulation prevents derived classes from advancing the enumerator unsafely
    private readonly IEnumerator<ITunableResultConsolidator> _gridSearch;
    
    /// <summary>
    /// Initializes the base brute force optimizer and materializes the search grid.
    /// </summary>
    /// <param name="frameRateHz">The inference frame rate.</param>
    /// <param name="classes">The target class mapping.</param>
    protected BruteForceGridOptimizer(double frameRateHz, ClassificationClass[] classes)
    {
        FrameRateHz = frameRateHz;
        Classes = classes;
        _gridSearch = GenerateGrid().GetEnumerator();
    }
    
    /// <inheritdoc />
    public ITunableResultConsolidator? SuggestNext(float? score) => _gridSearch.MoveNext() ? _gridSearch.Current : null;
    
    /// <summary>
    /// Yields the exhaustive sequence of instantiated consolidators representing the specific hyperparameter grid.
    /// </summary>
    /// <returns>An enumerable stream of consolidator candidates.</returns>
    protected abstract IEnumerable<ITunableResultConsolidator> GenerateGrid();

    /// <summary>
    /// Safely releases the state machine generated by the internal iterator block.
    /// </summary>
    public void Dispose()
    {
        _gridSearch.Dispose();
        GC.SuppressFinalize(this);
    }
}